# Generated by Django 4.2.27 on 2025-12-29 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_gender_user_relationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='core.post'),
        ),
    ]
